import { type Product } from "./product.types";

/**
 * Static placeholder catalog. Replace with data fetched from a CMS / commerce
 * API once integration begins — the UI layer only depends on the `Product`
 * type, so swapping the data source later won't require touching components.
 */
export const featuredProducts: Product[] = [
  {
    id: "fp-1",
    slug: "aoi-gyuto-210",
    image: "/dev-images/products/aoi-gyuto-210.jpg",
    name: "Aoi Gyuto 210mm",
    category: "Chef's Knife",
    price: 248,
    compareAtPrice: 310,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 36,
    badge: "sale",
  },
  {
    id: "fp-2",
    slug: "sumi-santoku-180",
    image: "/dev-images/products/sumi-santoku-180.jpg",
    name: "Sumi Santoku 180mm",
    category: "Multi-Purpose",
    price: 162,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 51,
  },
  {
    id: "fp-3",
    slug: "kuro-bunka-190",
    image: "/dev-images/products/kuro-bunka-190.jpg",
    name: "Kuro Bunka 190mm",
    category: "Multi-Purpose",
    price: 176,
    compareAtPrice: 220,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 19,
    badge: "sale",
  },
  {
    id: "fp-4",
    slug: "tsuchime-nakiri-165",
    image: "/dev-images/products/tsuchime-nakiri-165.jpg",
    name: "Tsuchime Nakiri 165mm",
    category: "Vegetable",
    price: 138,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 12,
    badge: "sold-out",
  },
];

export const newArrivals: Product[] = [
  {
    id: "na-1",
    slug: "hibana-petty-120",
    image: "/dev-images/products/hibana-petty-120.jpg",
    name: "Hibana Petty 120mm",
    category: "Paring",
    price: 86,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-2",
    slug: "shirobana-sujihiki-240",
    image: "/dev-images/products/shirobana-sujihiki-240.jpg",
    name: "Shirobana Sujihiki 240mm",
    category: "Slicer",
    price: 254,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-3",
    slug: "ginko-cutting-board-s",
    image: "/dev-images/products/ginko-cutting-board-s.jpg",
    name: "Ginko Cutting Board — Small",
    category: "Accessories",
    price: 58,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-4",
    slug: "ren-kitchen-tweezers",
    image: "/dev-images/products/ren-kitchen-tweezers.jpg",
    name: "Ren Kitchen Tweezers",
    category: "Accessories",
    price: 46,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
];

export const monthlyPick: Product = {
  id: "mp-1",
  slug: "ginrei-santoku-170",
  image: "/dev-images/products/ginrei-santoku-170.jpg",
  name: "Ginrei Santoku 170mm",
  category: "Knife of the Month",
  price: 136,
  compareAtPrice: 170,
  currency: "EUR",
  rating: 5,
  reviewCount: 8,
  badge: "sale",
};

export const japaneseKnives: Product[] = [
  {
    id: "jk-1",
    slug: "aoi-gyuto-210",
    image: "/dev-images/products/aoi-gyuto-210.jpg",
    name: "Aoi Gyuto 210mm",
    category: "Chef's Knife",
    price: 248,
    compareAtPrice: 310,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 36,
    badge: "sale",
    description:
      "A versatile 210mm gyuto forged from blue carbon steel (Aogami #2) with a tsuchime finish. Holds a keen edge through long prep sessions and feels balanced from the very first cut.",
    highlights: [
      "Aogami #2 carbon core, 62 HRC",
      "Hand-forged tsuchime (hammered) finish",
      "Octagonal magnolia wood handle",
      "Free engraving available at checkout",
    ],
    specs: [
      { label: "Blade length", value: "210 mm" },
      { label: "Steel", value: "Aogami #2 (Blue Carbon)" },
      { label: "Hardness", value: "62 HRC" },
      { label: "Handle", value: "Magnolia / Buffalo horn" },
      { label: "Weight", value: "178 g" },
      { label: "Maker", value: "Pisau Pedia" },
    ],
    galleryLabels: ["Front", "Spine", "Handle", "Edge detail"],
  },
  {
    id: "jk-2",
    slug: "sumi-santoku-180",
    image: "/dev-images/products/sumi-santoku-180.jpg",
    name: "Sumi Santoku 180mm",
    category: "Santoku",
    price: 162,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 51,
  },
  {
    id: "jk-3",
    slug: "kuro-bunka-190",
    image: "/dev-images/products/kuro-bunka-190.jpg",
    name: "Kuro Bunka 190mm",
    category: "Bunka",
    price: 176,
    compareAtPrice: 220,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 19,
    badge: "sale",
  },
  {
    id: "jk-4",
    slug: "tsuchime-nakiri-165",
    image: "/dev-images/products/tsuchime-nakiri-165.jpg",
    name: "Tsuchime Nakiri 165mm",
    category: "Nakiri",
    price: 138,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 12,
  },
  {
    id: "jk-5",
    slug: "shirobana-sujihiki-240",
    image: "/dev-images/products/shirobana-sujihiki-240.jpg",
    name: "Shirobana Sujihiki 240mm",
    category: "Slicer",
    price: 254,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 7,
  },
  {
    id: "jk-6",
    slug: "hibana-petty-120",
    image: "/dev-images/products/hibana-petty-120.jpg",
    name: "Hibana Petty 120mm",
    category: "Petty",
    price: 86,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 9,
    badge: "new",
  },
  {
    id: "jk-7",
    slug: "yama-gyuto-240",
    image: "/dev-images/products/yama-gyuto-240.jpg",
    name: "Yama Gyuto 240mm",
    category: "Chef's Knife",
    price: 296,
    currency: "EUR",
    rating: 5,
    reviewCount: 22,
  },
  {
    id: "jk-8",
    slug: "mori-nakiri-170",
    image: "/dev-images/products/mori-nakiri-170.jpg",
    name: "Mori Nakiri 170mm",
    category: "Nakiri",
    price: 148,
    compareAtPrice: 185,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 5,
    badge: "sale",
  },
];


export const accessories: Product[] = [
  {
    id: "acc-1",
    slug: "leather-knife-roll-10",
    image: "/dev-images/products/leather-knife-roll-10.jpg",
    name: "Chef's Leather Knife Roll — 10 Slots",
    maker: "Pisau Pedia",
    category: "Knife Bags & Rolls",
    price: 120,
    compareAtPrice: 150,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 42,
    badge: "sale",
    description:
      "Full-grain vegetable-tanned leather roll with 10 padded slots. Keeps your blades protected on the go.",
    highlights: [
      "Full-grain vegetable-tanned cowhide",
      "10 individual padded knife slots",
      "Brass buckle closure",
      "Fits blades up to 300 mm",
    ],
    specs: [
      { label: "Material", value: "Full-grain leather" },
      { label: "Slots", value: "10" },
      { label: "Max blade length", value: "300 mm" },
      { label: "Weight", value: "680 g" },
    ],
  },
  {
    id: "acc-2",
    slug: "magnetic-knife-holder-walnut",
    image: "/dev-images/products/magnetic-knife-holder-walnut.jpg",
    name: "Magnetic Knife Holder — Walnut",
    maker: "Pisau Pedia",
    category: "Knife Holders",
    price: 92,
    compareAtPrice: 115,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 38,
    badge: "sale",
  },
  {
    id: "acc-3",
    slug: "hasegawa-cutting-board-m",
    image: "/dev-images/products/hasegawa-cutting-board-m.jpg",
    name: "Hasegawa Soft Cutting Board — Medium",
    maker: "Hasegawa",
    category: "Cutting Boards",
    price: 68,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 55,
  },
  {
    id: "acc-4",
    slug: "hasegawa-cutting-board-l",
    image: "/dev-images/products/hasegawa-cutting-board-l.jpg",
    name: "Hasegawa Soft Cutting Board — Large",
    maker: "Hasegawa",
    category: "Cutting Boards",
    price: 88,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 33,
  },
  {
    id: "acc-5",
    slug: "end-grain-walnut-board",
    image: "/dev-images/products/end-grain-walnut-board.jpg",
    name: "End Grain Walnut Cutting Board",
    maker: "Pisau Pedia",
    category: "Cutting Boards",
    price: 135,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 21,
    badge: "new",
  },
  {
    id: "acc-6",
    slug: "benriner-mandoline-slicer",
    image: "/dev-images/products/benriner-mandoline-slicer.jpg",
    name: "Benriner Mandoline Slicer",
    maker: "Benriner",
    category: "Mandoline Slicers",
    price: 38,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: "acc-7",
    slug: "benriner-mandoline-pro",
    image: "/dev-images/products/benriner-mandoline-pro.jpg",
    name: "Benriner Mandoline Slicer — Pro",
    maker: "Benriner",
    category: "Mandoline Slicers",
    price: 55,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 29,
  },
  {
    id: "acc-8",
    slug: "chiba-mandoline-slicer",
    image: "/dev-images/products/chiba-mandoline-slicer.jpg",
    name: "Chiba Mandoline Slicer",
    maker: "Chiba",
    category: "Mandoline Slicers",
    price: 48,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 18,
  },
  {
    id: "acc-9",
    slug: "wooden-saya-gyuto-210",
    image: "/dev-images/products/wooden-saya-gyuto-210.jpg",
    name: "Wooden Saya — Gyuto 210mm",
    maker: "Pisau Pedia",
    category: "Knife Sheaths",
    price: 21,
    compareAtPrice: 26,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 44,
    badge: "sale",
  },
  {
    id: "acc-10",
    slug: "wooden-saya-santoku-180",
    image: "/dev-images/products/wooden-saya-santoku-180.jpg",
    name: "Wooden Saya — Santoku 180mm",
    maker: "Pisau Pedia",
    category: "Knife Sheaths",
    price: 18,
    compareAtPrice: 23,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 31,
    badge: "sale",
  },
  {
    id: "acc-11",
    slug: "wooden-saya-nakiri-165",
    image: "/dev-images/products/wooden-saya-nakiri-165.jpg",
    name: "Wooden Saya — Nakiri 165mm",
    maker: "Pisau Pedia",
    category: "Knife Sheaths",
    price: 17,
    compareAtPrice: 22,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 19,
    badge: "sale",
  },
  {
    id: "acc-12",
    slug: "kitchen-tweezers-stainless",
    image: "/dev-images/products/kitchen-tweezers-stainless.jpg",
    name: "Kitchen Tweezers — Stainless 300mm",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 24,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 16,
  },
  {
    id: "acc-13",
    slug: "fish-bone-tweezers",
    image: "/dev-images/products/fish-bone-tweezers.jpg",
    name: "Fish Bone Tweezers",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 18,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 22,
  },
  {
    id: "acc-14",
    slug: "kitchen-scissors-stainless",
    image: "/dev-images/products/kitchen-scissors-stainless.jpg",
    name: "Kitchen Scissors — Stainless",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 35,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 28,
  },
  {
    id: "acc-15",
    slug: "small-scissors-40mm",
    image: "/dev-images/products/small-scissors-40mm.jpg",
    name: "Small Scissors 40mm",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 10,
    currency: "EUR",
    rating: 4.2,
    reviewCount: 12,
  },
  {
    id: "acc-16",
    slug: "fish-scaler-brass",
    image: "/dev-images/products/fish-scaler-brass.jpg",
    name: "Fish Scaler — Brass",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 28,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 9,
    badge: "new",
  },
  {
    id: "acc-17",
    slug: "leather-knife-bag-5",
    image: "/dev-images/products/leather-knife-bag-5.jpg",
    name: "Leather Knife Bag — 5 Slots",
    maker: "Pisau Pedia",
    category: "Knife Bags & Rolls",
    price: 85,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 17,
  },
  {
    id: "acc-18",
    slug: "canvas-knife-roll-8",
    image: "/dev-images/products/canvas-knife-roll-8.jpg",
    name: "Waxed Canvas Knife Roll — 8 Slots",
    maker: "Pisau Pedia",
    category: "Knife Bags & Rolls",
    price: 78,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 24,
  },
  {
    id: "acc-19",
    slug: "magnetic-knife-holder-oak",
    image: "/dev-images/products/magnetic-knife-holder-oak.jpg",
    name: "Magnetic Knife Holder — Oak",
    maker: "Pisau Pedia",
    category: "Knife Holders",
    price: 82,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: "acc-20",
    slug: "sushi-making-kit",
    image: "/dev-images/products/sushi-making-kit.jpg",
    name: "Sushi Making Kit — Bamboo",
    maker: "Pisau Pedia",
    category: "Kitchen Tools",
    price: 32,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 41,
  },
  {
    id: "acc-21",
    slug: "lindy-cutting-board-hinoki",
    name: "Lindy Cutting Board — Hinoki Cypress",
    maker: "Lindy",
    category: "Cutting Boards",
    price: 95,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 13,
  },
  {
    id: "acc-22",
    slug: "suncraft-mandoline-v",
    image: "/dev-images/products/suncraft-mandoline-v.jpg",
    name: "Suncraft V-Shape Mandoline Slicer",
    maker: "Suncraft",
    category: "Mandoline Slicers",
    price: 42,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 11,
    badge: "new",
  },
  {
    id: "acc-23",
    slug: "wooden-saya-petty-150",
    image: "/dev-images/products/wooden-saya-petty-150.jpg",
    name: "Wooden Saya — Petty 150mm",
    maker: "Pisau Pedia",
    category: "Knife Sheaths",
    price: 15,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 14,
  },
  {
    id: "acc-24",
    slug: "knife-edge-guard-set",
    image: "/dev-images/products/knife-edge-guard-set.jpg",
    name: "Universal Edge Guard Set — 3 Pieces",
    maker: "Pisau Pedia",
    category: "Knife Sheaths",
    price: 22,
    currency: "EUR",
    rating: 4.1,
    reviewCount: 8,
    badge: "sold-out",
  },
];
