import { type Product } from "./product.types";

/**
 * Static placeholder catalog. Replace with data fetched from a CMS / commerce
 * API once integration begins — the UI layer only depends on the `Product`
 * type, so swapping the data source later won't require touching components.
 */
export const featuredProducts: Product[] = [
  {
    id: "fp-1",
    slug: "aoi-gyuto-210",
    name: "Aoi Gyuto 210mm",
    category: "Chef's Knife",
    price: 248,
    compareAtPrice: 310,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 36,
    badge: "sale",
  },
  {
    id: "fp-2",
    slug: "sumi-santoku-180",
    name: "Sumi Santoku 180mm",
    category: "Multi-Purpose",
    price: 162,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 51,
  },
  {
    id: "fp-3",
    slug: "kuro-bunka-190",
    name: "Kuro Bunka 190mm",
    category: "Multi-Purpose",
    price: 176,
    compareAtPrice: 220,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 19,
    badge: "sale",
  },
  {
    id: "fp-4",
    slug: "tsuchime-nakiri-165",
    name: "Tsuchime Nakiri 165mm",
    category: "Vegetable",
    price: 138,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 12,
    badge: "sold-out",
  },
];

export const newArrivals: Product[] = [
  {
    id: "na-1",
    slug: "hibana-petty-120",
    name: "Hibana Petty 120mm",
    category: "Paring",
    price: 86,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-2",
    slug: "shirobana-sujihiki-240",
    name: "Shirobana Sujihiki 240mm",
    category: "Slicer",
    price: 254,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-3",
    slug: "ginko-cutting-board-s",
    name: "Ginko Cutting Board — Small",
    category: "Accessories",
    price: 58,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
  {
    id: "na-4",
    slug: "ren-kitchen-tweezers",
    name: "Ren Kitchen Tweezers",
    category: "Accessories",
    price: 46,
    currency: "EUR",
    rating: 0,
    reviewCount: 0,
    badge: "new",
  },
];

export const monthlyPick: Product = {
  id: "mp-1",
  slug: "ginrei-santoku-170",
  name: "Ginrei Santoku 170mm",
  category: "Knife of the Month",
  price: 136,
  compareAtPrice: 170,
  currency: "EUR",
  rating: 5,
  reviewCount: 8,
  badge: "sale",
};

export const japaneseKnives: Product[] = [
  {
    id: "jk-1",
    slug: "aoi-gyuto-210",
    name: "Aoi Gyuto 210mm",
    category: "Chef's Knife",
    price: 248,
    compareAtPrice: 310,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 36,
    badge: "sale",
    description:
      "A versatile 210mm gyuto forged from blue carbon steel (Aogami #2) with a tsuchime finish. Holds a keen edge through long prep sessions and feels balanced from the very first cut.",
    highlights: [
      "Aogami #2 carbon core, 62 HRC",
      "Hand-forged tsuchime (hammered) finish",
      "Octagonal magnolia wood handle",
      "Free engraving available at checkout",
    ],
    specs: [
      { label: "Blade length", value: "210 mm" },
      { label: "Steel", value: "Aogami #2 (Blue Carbon)" },
      { label: "Hardness", value: "62 HRC" },
      { label: "Handle", value: "Magnolia / Buffalo horn" },
      { label: "Weight", value: "178 g" },
      { label: "Maker", value: "Tanaka Forge, Sakai" },
    ],
    galleryLabels: ["Front", "Spine", "Handle", "Edge detail"],
  },
  {
    id: "jk-2",
    slug: "sumi-santoku-180",
    name: "Sumi Santoku 180mm",
    category: "Santoku",
    price: 162,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 51,
  },
  {
    id: "jk-3",
    slug: "kuro-bunka-190",
    name: "Kuro Bunka 190mm",
    category: "Bunka",
    price: 176,
    compareAtPrice: 220,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 19,
    badge: "sale",
  },
  {
    id: "jk-4",
    slug: "tsuchime-nakiri-165",
    name: "Tsuchime Nakiri 165mm",
    category: "Nakiri",
    price: 138,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 12,
  },
  {
    id: "jk-5",
    slug: "shirobana-sujihiki-240",
    name: "Shirobana Sujihiki 240mm",
    category: "Slicer",
    price: 254,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 7,
  },
  {
    id: "jk-6",
    slug: "hibana-petty-120",
    name: "Hibana Petty 120mm",
    category: "Petty",
    price: 86,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 9,
    badge: "new",
  },
  {
    id: "jk-7",
    slug: "yama-gyuto-240",
    name: "Yama Gyuto 240mm",
    category: "Chef's Knife",
    price: 296,
    currency: "EUR",
    rating: 5,
    reviewCount: 22,
  },
  {
    id: "jk-8",
    slug: "mori-nakiri-170",
    name: "Mori Nakiri 170mm",
    category: "Nakiri",
    price: 148,
    compareAtPrice: 185,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 5,
    badge: "sale",
  },
];
